<a href="https://colab.research.google.com/github/Aditigv/AI-ML-Lab/blob/main/ML_AI_lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
list1=[1.0,2.0,3.0,4.0,5.0]
npy_array=np.array(list1, dtype=np.float64)
#convert list to array(or something like matrix)
print("Array dimension =",npy_array.ndim) # get dimension of array
a=np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float64)
# np.array - like creating matrix
print("Dimension of array 'a'=",a.ndim)
print("Matrix shape=",a.shape)
print("Total elem in arrary=",a.size) # total elem in an array
print("byte size of each element in array= ",a.itemsize) # each elem's size(in bytes)
print("Element datatype=",a.dtype.name) # get elem data type name
type(a) # <class 'ndarray'> ndim array
np.indices((3,5)) # get index matrix for each elem in 3x5 matrix

Array dimension = 1
Dimension of array 'a'= 2
Matrix shape= (3, 3)
Total elem in arrary= 9
byte size of each element in array=  8
Element datatype= float64


array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [16]:
import numpy as np 
 
print("eye matrix=",np.eye(4))  # get eye matrix  
print("identity matrix=",np.identity(3))  # like eye function 
 
z = np.zeros((3,4), dtype=int) 
print("null matrix=", z)
z = np.ones((3,4), dtype=np.float64) 
print("unit matrix=",z)
 
z=np.random.random(())
print(z)
z=np.random.uniform(-3, 5, (5,6))  
print(z)
# get 5x6 matrix with random # from -3 to 5 for each elem 

eye matrix= [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
identity matrix= [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
null matrix= [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
unit matrix= [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0.6247183452948623
[[ 2.96642625  2.04979361 -2.36328601  1.07488725 -1.84258687  2.28415901]
 [ 2.9075253   0.47296618  4.98679969  2.97515398 -1.15143877  1.21888202]
 [-1.40838389  1.24198031 -2.66184688  1.6736604   4.88014134  2.86269965]
 [ 0.81080891 -0.99865209 -0.68341959  1.70966174 -2.03687135 -1.22936232]
 [ 3.83550418  0.43547374  0.31913879  2.20183582  0.97304055 -1.92076626]]
