<a href="https://colab.research.google.com/github/Aditigv/AI-ML-Lab/blob/main/ML_AI_lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
list1=[1.0,2.0,3.0,4.0,5.0]
npy_array=np.array(list1, dtype=np.float64)
#convert list to array(or something like matrix)
print("Array dimension =",npy_array.ndim) # get dimension of array
a=np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float64)
# np.array - like creating matrix
print("Dimension of array 'a'=",a.ndim)
print("Matrix shape=",a.shape)
print("Total elem in arrary=",a.size) # total elem in an array
print("byte size of each element in array= ",a.itemsize) # each elem's size(in bytes)
print("Element datatype=",a.dtype.name) # get elem data type name
type(a) # <class 'ndarray'> ndim array
np.indices((3,5)) # get index matrix for each elem in 3x5 matrix

Array dimension = 1
Dimension of array 'a'= 2
Matrix shape= (3, 3)
Total elem in arrary= 9
byte size of each element in array=  8
Element datatype= float64


array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [19]:
import numpy as np 
 
print("eye matrix=\n",np.eye(4))  # get eye matrix  
print("identity matrix=\n",np.identity(3))  # like eye function 
 
z = np.zeros((3,4), dtype=int) 
print("null matrix=\n", z)
z = np.ones((3,4), dtype=np.float64) 
print("unit matrix=\n",z)
 
z=np.random.random(())
print(z)
z=np.random.uniform(-3, 5, (5,6))  
print(z)
# get 5x6 matrix with random # from -3 to 5 for each elem 

eye matrix=
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
identity matrix=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
null matrix=
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
unit matrix=
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0.404921882908576
[[ 2.62580582 -2.70958458 -0.56039348  3.16280295 -1.37856049 -1.76626363]
 [ 4.22393758  2.51150599 -0.63410733  2.07268553 -0.37840067  4.02462833]
 [ 4.17860533  2.8077975   1.1263767   1.84911762  2.50392829  4.34091012]
 [ 0.0467028   3.87775108  1.48208794  4.28093098 -1.83835855  0.26278111]
 [ 1.56028779  1.2418418   3.90758927 -0.84923908  1.37226126  2.75486418]]
